---
name: Date-DateTime-Easy
version: 0.020
author:
  - 'Robert Krimen, C<< <rkrimen at cpan.org> >>'
abstract: Quickly and easily create a Date::DateTime object (by parsing almost anything)
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Date::Manip: 0
  DateTime: 0
build_requires:
  Test::More: 0
provides:
  Date::DateTime::Easy:
    file: lib/Date/DateTime/Easy.pm
    version: 0.020
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
